FROM node:18-alpine

WORKDIR /app

# Копируем package.json
COPY package*.json ./
RUN npm install

# Копируем остальные файлы
COPY . .

# Vite dev server порт по умолчанию 5173
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]